name: Setup organization

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-organization:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: View context attributes
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./lib/index.js')
            script({github, context})